//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_AdminOperateLogs
    {
        public int LogId { get; set; }
        public int Uid { get; set; }
        public string NickName { get; set; }
        public short AdminGId { get; set; }
        public string AdminGTitle { get; set; }
        public string Operation { get; set; }
        public string Description { get; set; }
        public string Ip { get; set; }
        public System.DateTime OperateTime { get; set; }
    }
}
