//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_CouponTypes
    {
        public int CouponTypeId { get; set; }
        public byte State { get; set; }
        public string Name { get; set; }
        public System.DateTime AddTime { get; set; }
        public string CouponImg { get; set; }
        public string ProductImg { get; set; }
        public string RegionIds { get; set; }
        public decimal Money { get; set; }
        public int DeliveryAreaId { get; set; }
        public System.DateTime UseStartTime { get; set; }
        public System.DateTime UseEndTime { get; set; }
        public string CouponTypeSn { get; set; }
        public string DeliveryAreaSn { get; set; }
        public decimal CostPrice { get; set; }
        public int IsCostPrice { get; set; }
        public int TemplateId { get; set; }
    }
}
