//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_MaterialLibrary
    {
        public int MaterialId { get; set; }
        public byte Type { get; set; }
        public string ShowName { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public int FileSize { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string FileUrl { get; set; }
    }
}
