//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_OrderActions
    {
        public int AId { get; set; }
        public int OId { get; set; }
        public int UId { get; set; }
        public string RealName { get; set; }
        public short AdminGId { get; set; }
        public string AdminGTitle { get; set; }
        public byte ActionType { get; set; }
        public System.DateTime ActionTime { get; set; }
        public string ActionDes { get; set; }
    }
}
