//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_Orders
    {
        public int OId { get; set; }
        public string OSn { get; set; }
        public int UId { get; set; }
        public byte OrderState { get; set; }
        public decimal ProductAmount { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal SurplusMoney { get; set; }
        public System.DateTime AddTime { get; set; }
        public string ShipSn { get; set; }
        public string ShiPsyStemName { get; set; }
        public string ShipFriendName { get; set; }
        public System.DateTime ShipTime { get; set; }
        public byte PayMode { get; set; }
        public string PaySn { get; set; }
        public string PaySystemName { get; set; }
        public string PayFriendName { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public short RegionId { get; set; }
        public string Consignee { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public decimal ShipFee { get; set; }
        public Nullable<int> Weight { get; set; }
        public string BuyerRemark { get; set; }
        public string Ip { get; set; }
        public bool IsDel { get; set; }
        public int OrderSource { get; set; }
        public byte Type { get; set; }
    }
}
