//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_OrderProducts
    {
        public int RecordId { get; set; }
        public int OId { get; set; }
        public int UId { get; set; }
        public string SId { get; set; }
        public int PId { get; set; }
        public string PSn { get; set; }
        public short CateId { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
        public string ShowImg { get; set; }
        public decimal ShopPrice { get; set; }
        public decimal CostPrice { get; set; }
        public int Weight { get; set; }
        public int RealCount { get; set; }
        public int BuyCount { get; set; }
        public int SendCount { get; set; }
        public System.DateTime AddTime { get; set; }
        public decimal ShipFee { get; set; }
    }
}
