//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_Regions
    {
        public short RegionId { get; set; }
        public string Name { get; set; }
        public string Spell { get; set; }
        public string ShortSpell { get; set; }
        public int DisplayOrder { get; set; }
        public short ParentId { get; set; }
        public byte Layer { get; set; }
        public short ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public short CityId { get; set; }
        public string CityName { get; set; }
    }
}
