//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_ShippingRegionsGroups
    {
        public int GroupId { get; set; }
        public int TemplateId { get; set; }
        public int DefaultNumber { get; set; }
        public int AddNumber { get; set; }
        public decimal Price { get; set; }
        public decimal AddPrice { get; set; }
    }
}
