//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_ShipAddresses
    {
        public int SAId { get; set; }
        public int UId { get; set; }
        public short RegionId { get; set; }
        public byte IsDefault { get; set; }
        public string Consignee { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Flag { get; set; }
    }
}
