//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LF_ShopPlatformEntities : DbContext
    {
        public LF_ShopPlatformEntities()
            : base("name=LF_ShopPlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LF_AdminActions> LF_AdminActions { get; set; }
        public virtual DbSet<LF_AdminGroups> LF_AdminGroups { get; set; }
        public virtual DbSet<LF_AdminOperateLogs> LF_AdminOperateLogs { get; set; }
        public virtual DbSet<LF_Banners> LF_Banners { get; set; }
        public virtual DbSet<LF_Brands> LF_Brands { get; set; }
        public virtual DbSet<LF_Categories> LF_Categories { get; set; }
        public virtual DbSet<LF_CouponDeliveryAreas> LF_CouponDeliveryAreas { get; set; }
        public virtual DbSet<LF_Coupons> LF_Coupons { get; set; }
        public virtual DbSet<LF_CouponTypeContents> LF_CouponTypeContents { get; set; }
        public virtual DbSet<LF_MaterialCategory> LF_MaterialCategory { get; set; }
        public virtual DbSet<LF_MaterialLibrary> LF_MaterialLibrary { get; set; }
        public virtual DbSet<LF_Oauth> LF_Oauth { get; set; }
        public virtual DbSet<LF_OrderActions> LF_OrderActions { get; set; }
        public virtual DbSet<LF_OrderProducts> LF_OrderProducts { get; set; }
        public virtual DbSet<LF_Orders> LF_Orders { get; set; }
        public virtual DbSet<LF_ProductImages> LF_ProductImages { get; set; }
        public virtual DbSet<LF_ProductStocks> LF_ProductStocks { get; set; }
        public virtual DbSet<LF_Regions> LF_Regions { get; set; }
        public virtual DbSet<LF_ShipAddresses> LF_ShipAddresses { get; set; }
        public virtual DbSet<LF_ShipCompanies> LF_ShipCompanies { get; set; }
        public virtual DbSet<LF_ShippingAppointRegions> LF_ShippingAppointRegions { get; set; }
        public virtual DbSet<LF_ShippingPrice> LF_ShippingPrice { get; set; }
        public virtual DbSet<LF_ShippingRegions> LF_ShippingRegions { get; set; }
        public virtual DbSet<LF_ShippingTemplates> LF_ShippingTemplates { get; set; }
        public virtual DbSet<LF_Users> LF_Users { get; set; }
        public virtual DbSet<LF_Products> LF_Products { get; set; }
        public virtual DbSet<LF_CouponTypes> LF_CouponTypes { get; set; }
        public virtual DbSet<LF_ShippingRegionsGroups> LF_ShippingRegionsGroups { get; set; }
    }
}
