//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_ShippingPrice
    {
        public int RecordId { get; set; }
        public int TemplateId { get; set; }
        public decimal StartPrice { get; set; }
        public decimal EndPrice { get; set; }
        public decimal Freight { get; set; }
        public decimal WithFree { get; set; }
        public int Type { get; set; }
        public decimal SPrice { get; set; }
        public decimal SFreight { get; set; }
    }
}
