//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianFa.ShopPlatform.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LF_Users
    {
        public int UId { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string PassWord { get; set; }
        public short AdminGId { get; set; }
        public string NickName { get; set; }
        public string Avatar { get; set; }
        public string Salt { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public byte Gender { get; set; }
    }
}
